"use client";

import { useEffect, useState } from "react";
import { WorkspacePage } from "@/components/require-auth";
import { api, type GenerationResult, type UniDocument } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

const FORMATS = [
  { id: "outline", label: "Paper outline" },
  { id: "literature", label: "Literature review skeleton" },
  { id: "methodology", label: "Methodology critique" },
  { id: "summary", label: "Paper summary" },
  { id: "questions", label: "Research questions" },
];

export default function ResearchPage() {
  const { token } = useAuth();
  const [topic, setTopic] = useState("");
  const [format, setFormat] = useState("outline");
  const [documents, setDocuments] = useState<UniDocument[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!token) return;
    api
      .documents(token)
      .then((list) => setDocuments(list.filter((item) => item.status === "ready")))
      .catch(() => undefined);
  }, [token]);

  async function generate(event: React.FormEvent) {
    event.preventDefault();
    if (!token || topic.trim().length < 2) return;
    setBusy(true);
    setError("");
    setResult(null);
    try {
      setResult(
        await api.research(token, {
          topic,
          format,
          document_ids: selected.length ? selected : undefined,
        }),
      );
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Generation failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <WorkspacePage
      title="Research workspace"
      description="Outline papers, review literature and critique methods — grounded in the papers you upload."
    >
      <form onSubmit={generate} className="card mb-8 space-y-4 p-5">
        <textarea
          className="field min-h-24 w-full"
          placeholder="Federated learning for privacy-preserving attendance analytics"
          value={topic}
          onChange={(event) => setTopic(event.target.value)}
        />
        <select
          className="field w-full sm:w-72"
          value={format}
          onChange={(event) => setFormat(event.target.value)}
        >
          {FORMATS.map((item) => (
            <option key={item.id} value={item.id}>
              {item.label}
            </option>
          ))}
        </select>

        {documents.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {documents.map((document) => {
              const active = selected.includes(document.id);
              return (
                <button
                  key={document.id}
                  type="button"
                  onClick={() =>
                    setSelected((current) =>
                      active ? current.filter((id) => id !== document.id) : [...current, document.id],
                    )
                  }
                  className={
                    active
                      ? "rounded-lg bg-primary px-3 py-1.5 text-xs text-primary-foreground"
                      : "rounded-lg border px-3 py-1.5 text-xs text-muted-foreground"
                  }
                >
                  {document.title}
                </button>
              );
            })}
          </div>
        ) : null}

        <button className="btn-primary px-4 py-2 text-sm" disabled={busy}>
          {busy ? "Working…" : "Generate"}
        </button>
      </form>

      {error ? <p className="mb-6 text-sm text-red-500">{error}</p> : null}

      {result ? (
        <article className="card p-5">
          <p className="mb-3 text-xs text-muted-foreground">Generated by {result.model}</p>
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
            {result.content}
          </pre>
          {result.citations.length > 0 ? (
            <ul className="mt-4 space-y-1 border-t pt-3 text-xs text-muted-foreground">
              {result.citations.map((citation, index) => (
                <li key={index}>
                  [{index + 1}] {citation.document_title} — page {citation.page}
                </li>
              ))}
            </ul>
          ) : null}
        </article>
      ) : null}
    </WorkspacePage>
  );
}
