"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { SiteHeader } from "@/components/site-header";
import { useAuth } from "@/lib/auth-context";

const quickActions = [
  { label: "Ask AI", hint: "Ready" },
  { label: "Upload PDF", hint: "Phase 3" },
  { label: "Study", hint: "Phase 4" },
  { label: "Code", hint: "Phase 4" },
  { label: "Research", hint: "Phase 4" },
  { label: "Career", hint: "Phase 4" },
  { label: "Campus", hint: "Phase 4" },
  { label: "Analyse performance", hint: "Phase 6" },
];

export default function DashboardPage() {
  const router = useRouter();
  const { user, loading } = useAuth();

  useEffect(() => {
    if (!loading && !user) router.replace("/login");
  }, [loading, user, router]);

  if (loading) {
    return (
      <div className="min-h-screen">
        <SiteHeader />
        <main className="mx-auto max-w-6xl px-5 py-16 text-sm text-muted-foreground">
          Loading your dashboard…
        </main>
      </div>
    );
  }

  if (!user) return null;

  const firstName = user.full_name.split(" ")[0];

  return (
    <div className="min-h-screen">
      <SiteHeader />

      <main className="mx-auto max-w-6xl px-5 py-10">
        <header>
          <h1 className="text-2xl font-semibold tracking-tight">Good to see you, {firstName}</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Signed in as {user.email} · {user.role.toLowerCase().replace("_", " ")}
          </p>
        </header>

        <section className="mt-8 grid gap-4 lg:grid-cols-3">
          <article className="card p-6 lg:col-span-2">
            <h2 className="font-semibold">Today&apos;s overview</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Classes, assignments, deadlines, announcements and events appear here once the
              academics and calendar modules land in Phase 6. Nothing is simulated in the meantime.
            </p>
            <ul className="mt-4 space-y-2 text-sm text-muted-foreground">
              <li className="rounded-lg border border-dashed p-3">Upcoming classes — not yet connected</li>
              <li className="rounded-lg border border-dashed p-3">Assignments and deadlines — not yet connected</li>
              <li className="rounded-lg border border-dashed p-3">Announcements — not yet connected</li>
            </ul>
          </article>

          <article className="card p-6">
            <h2 className="font-semibold">AI insights</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Performance trends and study nudges are generated by the Academic Performance Agent.
              They will appear here once that agent is implemented.
            </p>
          </article>
        </section>

        <section className="mt-6">
          <h2 className="font-semibold">Quick actions</h2>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {quickActions.map((action) => (
              <div key={action.label} className="card flex items-center justify-between p-4">
                <span className="text-sm font-medium">{action.label}</span>
                <span className="rounded-full bg-surface-muted px-2 py-1 text-xs text-muted-foreground">
                  {action.hint}
                </span>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-6 grid gap-4 lg:grid-cols-2">
          <article className="card p-6">
            <h2 className="font-semibold">Academic context</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Your degree, branch, semester and interests help every agent answer in context. You can
              view, edit or clear this at any time.
            </p>
            <dl className="mt-4 grid grid-cols-2 gap-3 text-sm">
              <div>
                <dt className="text-muted-foreground">Degree</dt>
                <dd>{user.profile?.degree ?? "Not set"}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Branch</dt>
                <dd>{user.profile?.branch ?? "Not set"}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Semester</dt>
                <dd>{user.profile?.semester ?? "Not set"}</dd>
              </div>
              <div>
                <dt className="text-muted-foreground">Department</dt>
                <dd>{user.profile?.department ?? "Not set"}</dd>
              </div>
            </dl>
          </article>

          <article className="card p-6">
            <h2 className="font-semibold">What is coming next</h2>
            <ol className="mt-3 space-y-2 text-sm text-muted-foreground">
              <li>Phase 2 — AI gateway, chat, streaming and the agent router.</li>
              <li>Phase 3 — Document upload, retrieval and cited answers.</li>
              <li>Phase 4 — Study, research, coding, career, document and campus agents.</li>
            </ol>
            <Link href="/" className="btn-ghost mt-4 text-sm">
              Back to overview
            </Link>
          </article>
        </section>
      </main>
    </div>
  );
}
